import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getMyCampaigns } from '../api/campaigns';
import { categoryLabel, formatCurrency, formatDate, getProgress, normalizeCampaign } from '../utils/campaigns';
import './MyCampaigns.css';

function Badge({ status }) { return <span className={`my-status my-status--${String(status || 'pending').toLowerCase()}`}>{status || 'Pending'}</span>; }

export default function MyCampaigns() {
  const [campaigns, setCampaigns] = useState([]); const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await getMyCampaigns(); const data = response.data || {}; setCampaigns((data.campaigns || []).map(normalizeCampaign)); setRequests(data.requests || []); } catch (requestError) { setError(requestError.response?.data?.message || 'Your campaigns could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  if (loading) return <main className="my-page"><p className="my-loading">Loading your campaigns…</p></main>;
  return <main className="my-page"><section className="my-heading"><div><p className="my-eyebrow">Your activity</p><h1>My campaigns</h1><p>Track every request and see how your live campaigns are progressing.</p></div><Link to="/create-campaign">Create a campaign</Link></section>{error && <div className="my-error" role="alert">{error}<button onClick={load}>Try again</button></div>}<section className="my-section"><div className="my-section-title"><h2>Campaign requests</h2><p>Requests are reviewed by the CareConnect team before they go live.</p></div>{requests.length ? <div className="my-request-list">{requests.map((request) => { const data = request.campaignData || request; return <article key={request._id} className="my-request"><div><div className="my-request-top"><h3>{data.title || 'Campaign request'}</h3><Badge status={request.status}/></div><p>{categoryLabel(data.category)} · {formatCurrency(data.goalAmount)} · submitted {formatDate(request.createdAt)}</p>{request.adminRemarks && <p className="my-remarks"><strong>Reviewer note:</strong> {request.adminRemarks}</p>}</div>{request.campaign && <Link to={`/campaigns/${request.campaign._id || request.campaign.id}`}>View campaign</Link>}</article>; })}</div> : <div className="my-empty"><h3>No campaign requests yet</h3><p>When you need support, submit a request for the NIT Raipur community to review.</p><Link to="/create-campaign">Start a request</Link></div>}</section><section className="my-section"><div className="my-section-title"><h2>Live and completed campaigns</h2><p>Campaigns you created after approval.</p></div>{campaigns.length ? <div className="my-campaign-grid">{campaigns.map((campaign) => { const progress = getProgress(campaign); return <article className="my-campaign-card" key={campaign.id}><div className="my-request-top"><Badge status={campaign.status}/><span>{formatDate(campaign.deadline)}</span></div><h3>{campaign.title}</h3><p>{categoryLabel(campaign.category)}</p><div className="my-progress"><i style={{ width: `${progress}%` }} /></div><div className="my-progress-copy"><strong>{formatCurrency(campaign.raisedAmount)}</strong><span>of {formatCurrency(campaign.goalAmount)}</span></div><Link to={`/campaigns/${campaign.id}`}>View details →</Link></article>; })}</div> : <div className="my-empty"><h3>Your approved campaigns will appear here</h3><p>We’ll email you as soon as a request is approved or needs attention.</p></div>}</section></main>;
}
